CREATE TABLE T_USER_GROUP
(
    USER_GROUP_ID SERIAL PRIMARY KEY,
    USER_GROUP_NAME TEXT NOT NULL
);

CREATE TABLE T_USER
(
    USER_ID SERIAL PRIMARY KEY,
    USER_FIRST_NAME TEXT NOT NULL,
    USER_LAST_NAME TEXT NOT NULL,
    USER_EMAIL TEXT NOT NULL,
    USER_GROUP_ID INT REFERENCES T_USER_GROUP(USER_GROUP_ID) NOT NULL
);

CREATE TABLE T_ORDER
(
    ORDER_ID SERIAL PRIMARY KEY,
    USER_GROUP_ID INT REFERENCES T_USER_GROUP(USER_GROUP_ID) NOT NULL
);

CREATE TABLE T_ORDER_DETAIL
(
    ORDER_DETAIL_ID SERIAL PRIMARY KEY,
    ORDER_ID INT REFERENCES T_ORDER(ORDER_ID) NOT NULL,
    USER_ID INT REFERENCES T_USER(USER_ID) NOT NULL,
    ITEM_NUMBER TEXT,
    ITEM_NAME TEXT,
    ITEM_QTY INT,
    IMAGE TEXT,
    IS_REMOVED BOOLEAN DEFAULT FALSE
);

INSERT INTO PUBLIC.T_USER_GROUP (USER_GROUP_NAME) VALUES ('FAMILY');
INSERT INTO PUBLIC.T_USER_GROUP (USER_GROUP_NAME) VALUES ('FRIENDS');

INSERT INTO PUBLIC.T_USER (USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_GROUP_ID) VALUES ('BOB','MILLER','BOB@LOBLAW.CA',1);
INSERT INTO PUBLIC.T_USER (USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_GROUP_ID) VALUES ('BILL','MILLER','BILL@LOBLAW.CA',1);
INSERT INTO PUBLIC.T_USER (USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_GROUP_ID) VALUES ('JILL','MILLER','JILL@LOBLAW.CA',1);

INSERT INTO PUBLIC.T_USER (USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_GROUP_ID) VALUES ('JAMES','SMITH','JAMES@LOBLAW.CA',2);
INSERT INTO PUBLIC.T_USER (USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_GROUP_ID) VALUES ('KAJA','EVARISTO','KAJA@LOBLAW.CA',2);

INSERT INTO PUBLIC.T_ORDER (USER_GROUP_ID) VALUES (1);

INSERT INTO PUBLIC.T_ORDER_DETAIL (ORDER_ID, USER_ID, ITEM_NUMBER, ITEM_NAME, ITEM_QTY) VALUES (1,1,'20545207_EA','MEAT',2);
INSERT INTO PUBLIC.T_ORDER_DETAIL (ORDER_ID, USER_ID, ITEM_NUMBER, ITEM_NAME, ITEM_QTY) VALUES (1,1,'20548511003_EA','APPLES',3);
INSERT INTO PUBLIC.T_ORDER_DETAIL (ORDER_ID, USER_ID, ITEM_NUMBER, ITEM_NAME, ITEM_QTY) VALUES (1,2,'20100644001_KG','COOKIES',1);